<?php
/**
 * Copyright © 2016 Magestore. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magestore\Shopbybrand\Block\Brandcategories $block */

$cats = $block->getAllCategories();
$categories = $cats['parent'];
$count=count($categories);
if($count|| count($cats['children'])){
    ?>
    <div class="brandscategories col">
        <div class="shopbybrand-title">
            <h1><?php echo __('Brand by Category') ?></h1>
        </div>
        <strong style="margin-left: 15px;margin-bottom: 30px; width: 100%"><a href="javascript:void(0)" cateId="" onclick="cateFilter(this)"><?php echo __('All Categories');?></a></strong>
        <ul>
            <?php
            $div = intval($count/4);
            if($count%4==3) $div++ ;
            if($count%4==1||$count%4==2) $div_more=$div+1;
            $j=0;
            $column=1;
            $i=0;
            foreach ($categories as $category) {
                if(isset($cats['children'][$category->getId()]))
                    $childs = $cats['children'][$category->getId()];
                else
                    $childs = array();
                $i++;
                $j++;
        ?>

            <?php if($j==1): ?>
            <ol class="list_1">
            <?php endif;?>

                <li id="cat-<?php echo $i; ?>">
                <?php if(count($childs)>1) : ?>
                        <a class="show-child">&nbsp;</a>
                <?php endif;?>
                        <a style="<?php if(count($childs)<=1): ?>padding-left:15px;<?php endif ;?>"
                           href="javascript:void(0)"
                           cateId="<?php echo $category->getId();?>"
                           onclick="cateFilter(this)"
                           id="a-cat-<?php echo $category->getId();?>"
                        >
                                <?php echo $category->getName(); ?>
                        </a>
                        <?php if(count($childs)>1) : ?>
                        <ul class="brand-child" style="display:none;">
                        <?php
                                foreach($childs as $child):
                                        if($child->getId() != $category->getId()):
                        ?>
                                <li class="child-cat">
                                        <a href="javascript:void(0)"
                                           cateId="<?php echo $child->getId();?>"
                                           onclick="cateFilter(this)"
                                           id="a-cat-<?php echo $child->getId();?>"
                                        >
                                                <?php echo $child->getName(); ?>
                                        </a>
                                </li>
                        <?php endif;endforeach;?>
                        </ul>
                        <?php endif; ?>
                </li>
            <?php if($count%4==1):if($column==1):if($j==$div_more):?></ol><?php $j=0;$column++;endif;endif;endif;?>
            <?php if($count%4==1):if($column!=1):if($j==$div&&$div>0): ?></ol><?php $j=0;$column++; endif;endif;endif;?>
            <?php if($count%4==2):if($column==1||$column==2):if($j==$div_more):?></ol><?php $j=0;$column++;endif;endif;endif;?>
            <?php if($count%4==2):if($column!=1&&$column!=2):if($j==$div&&$div>0):?></ol><?php $j=0;$column++;endif;endif;endif;?>
            <?php if($count%4==3||$count%4==0): if($j==$div): ?></ol><?php $j=0;$column++;  endif;endif;?>
            <?php if($count%4==3): if($column==4):if($j==$div-1&&$div>1): ?></ol><?php endif; endif;endif;?>
            <?php
            }?>
        </ul>
        <script>
            require(['jquery'], function($) {
                var curentActiveCate = null;
                var curentFilter = null;
                window.cateFilter = function (el) {
                    if (curentActiveCate)
                        curentActiveCate.removeClass('isActiveCate');
                    $(el).addClass('isActiveCate');
                    curentActiveCate = $(el);
                    brandCateFilter();
                };
                window.brandCateFilter = function (){
                    var cat = '';
                    var char = '';

                    if(curentActiveCate&&curentActiveCate.attr('cateId')!='')
                        cat = '.c'+curentActiveCate.attr('cateId');

                    $('li.list_1').each(function () {
                        $(this).hide();
                    });
                    $('li.list_1' + cat + char).each(function () {
                        $(this).show();
                    });
                    if ($('.brandslist'))
                        $('.brandslist').each(function () {
                            console.log('.brandslist#' + $(this).attr('id') + ' li.list_1' + cat + char);
                            if (!$('.brandslist#' + $(this).attr('id') + ' li.list_1' + cat + char).length)
                                $(this).hide();
                            else
                                $(this).show();
                        });

                    brandLoading($('li.list_1' + cat + char).length);
                }

                window.brandLoading = function (list){
                    $('.brands ul').first().hide();
                    $('.brand-ajax-loading img').first().show();
                    $('.brand-not-found').first().hide();
                    setTimeout(function () {
                        $('.brand-ajax-loading img').first().hide();
                        if (list)
                            $('.brands ul').first().show();
                        else
                            $('.brand-not-found').first().show();
                    }, 2000);
                }


                $('.show-child').click(function () {
                    var showChild = $(this).nextAll('ul.brand-child');
                    if ($(this).hasClass('child_active')) {
                        $(this).removeClass('child_active');
                        showChild.hide();
                    }
                    else {
                        $(this).addClass('child_active');
                        showChild.show();
                    }
                });
            });
        </script>
    </div>
<?php  }?>