<?php
/**
 * Copyright © 2016 Magestore. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magestore\Shopbybrand\Block\Featureproduct $block */

$display = $block->getSystemConfig()->isDisplayFeatureProduct();
if($display){
    $featuredProducts = $block->getFeaturedProducts();
    $showAsSlider = true;
    $logo_width = 125;
    $logo_height = 125;
    $numberOfFeaturedProducts = 0;
    $brandWidth = $logo_width +50;
    ?>

    <?php if (count($featuredProducts)): ?>
        <div class="featuredbrands col" style="">
            <div class="shopbybrand-title">
                <h1><?php echo __('Featured Products');?></h1>
            </div>
            <div id="ca-container" class="ca-container" style="overflow: hidden;padding: 0px 50px; box-sizing: content-box;">
                <div class="ca-nav"><span class="ca-nav-prev" onclick="brandNavPrev()">Previous</span><span class="ca-nav-next" onclick="brandNavNext();">Next</span></div>
                <div class="ca-wrapper" style="overflow: hidden;">
                    <?php
                    foreach ($featuredProducts as $featuredProduct) :
                        $_item = $block->getItem($featuredProduct->getId());
                        $image = 'category_page_list';
                        $_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
                        $img = $_imagehelper->init($_item, $image)->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(145,112)->getUrl();
                        ?>
                        <div class="ca-item ca-item-">
                            <div class="ca-item-main">
                                <a href="<?php echo $block->getProductUrl($featuredProduct); ?>">
                                    <div class="brand-logo" style="margin-bottom: 5px;margin-top: 5px;">
                                        <img src="<?php echo $img; ?>" />
                                    </div>
                                    <div style="display: block;">
                                        <?php echo $featuredProduct->getName(); ?>
                                    </div>
                                </a>
                            </div>
                        </div>
                        <?php
                    endforeach;
                    ?>
                </div>
            </div>
            <script type="text/javascript">
                require(['jquery'], function($) {
                    var countFeaturedBrands = <?php echo count($featuredProducts);?>;
                    var brandWidth = <?php echo $brandWidth;?>;
                    var running = false;
                    var featuredbrandsWidth = $('.featuredbrands').first().width() -50;
                    var numberofbrand = Math.floor(featuredbrandsWidth/brandWidth);

                    numberofbrand = (numberofbrand<=countFeaturedBrands)?numberofbrand:countFeaturedBrands;
                    $('#ca-container').css('width', numberofbrand*brandWidth +"px");
                    window.onresize = brandresize;
                    function brandresize(){
                        featuredbrandsWidth = $('.featuredbrands').first().width()  -50;
                        numberofbrand = Math.floor(featuredbrandsWidth/brandWidth);
                        numberofbrand = (numberofbrand<=countFeaturedBrands)?numberofbrand:countFeaturedBrands;
                        $('#ca-container').css('width', numberofbrand*brandWidth +"px");
                    }
                    $('#ca-container .ca-item').each(function (index) {
                        $(this).css('position','absolute');
                        $(this).css('left',brandWidth * index + 'px');
                    });
                    window.brandNavNext = function (e) {
                        if (running)
                            return;
                        running = true;
                        $('#ca-container .ca-wrapper').first().append($('#ca-container .ca-item').first().clone()[0].outerHTML);
                        $('#ca-container .ca-item').each(function (index) {
                            $(this).css('left',brandWidth * index + 'px')  ;
                        });
                        var i = 1;
                        var interval = setInterval(function () {
                            if (i <= 10) {
                                $('.ca-item').each(function (index) {
                                    $(this).css('left',(index - 0.1 * i) * brandWidth + 'px');
                                });
                                i++;
                            } else {
                                $('#ca-container .ca-item').first().remove();
                                clearInterval(interval);
                                running = false;
                            }
                        }, 30);
                    }

                    window.brandNavPrev = function (e) {
                        if (running)
                            return;
                        running = true;
                        $('#ca-container .ca-wrapper').first().append($('#ca-container .ca-item').last().clone()[0].outerHTML);
                        $('#ca-container .ca-item').each(function (index) {
                            $(this).css('left',brandWidth * (index - 1) + 'px')  ;
                        });
                        var i = 1;
                        var interval = setInterval(function () {
                            if (i <= 10) {
                                $('.ca-item').each(function (index) {
                                    $(this).css('left',(index + 0.1 * i - 1) * brandWidth + 'px') ;
                                });
                                i++;
                            } else {
                                $('#ca-container .ca-item').last().remove();
                                clearInterval(interval);
                                running = false;
                            }
                        }, 30);
                    }
                });
                setInterval( function(){
                    brandNavNext();
                }, 2500);
            </script>
        </div>
    <?php endif; ?>
<?php } ?>
