<?php
/**
 * Copyright © 2016 Magestore. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magestore\Shopbybrand\Block\Searchbox $block */

?>
<div id="brand_search_box">
    <input type="text" class="brandsearch" id="brandsearch" autofocus="autofocus" autocorrect="off" autocomplete="off" placeholder="<?php echo __('Search by name'); ?>">
    <ul id="searchbrand" class="searchbrand"></ul>
</div>
<script type="text/javascript" charset="utf-8">

    var searchWidth = 35;
    var brands = <?php echo json_encode($block->getSearchData()); ?>;
    var brandIndex = 0;
    require(['jquery'], function($) {
        $('#brandsearch').on("input", null, null, function (el) {
            $('#searchbrand').html('');
            var count = 0;
            for(var i = 0; i < brands.length;i++){
                if ( brands[i].n.toLowerCase().search(el.target.value.toLowerCase()) != -1) {
                    count++;
                    $('#searchbrand').append('<li  onclick="redirect(\'' + brands[i].k + '\',\'' + brands[i].k + '\')">' + brands[i].n + '</li>');
                }
            }
            brandIndex = 0;
            if (count) {
                $('#searchbrand li').first().addClass('selected');
            }
        });
        var click = $('body').first().click(function (event) {
            if (event.target.id == 'brandsearch' || event.target.id == 'searchbrand')
                return;
            else $('#searchbrand').html('');
        });

        $('#brandsearch').keyup(function (event) {
            if (event.keyCode == 38 || event.keyCode == 40) {
                if ($F('brandsearch') == '' && !$$('#searchbrand li').length)
                    brands.each(function (el) {
                        $('searchbrand').insert('<li  onclick="redirect(\'' + el.k + '\',\'' + el.n + '\')">' + el.n + '</li>');
                    });
                $$('#searchbrand li')[brandIndex].removeClassName('selected');
                getSelectedIndex(event.keyCode);
                $$('#searchbrand li')[brandIndex].addClassName('selected');
                searchScroll();
                $('brandsearch').value = $$('#searchbrand li.selected').first().textContent;
            }
            if (event.keyCode == 13) {
                $('#brandsearch').value = '';
                if ($('#searchbrand li.selected').first())
                    $('#searchbrand li.selected').first().click();
            }
        });
        window.searchScroll = function() {
            if ($('searchbrand').scrollTop > brandIndex * searchWidth)
                $('searchbrand').scrollTop = brandIndex * searchWidth;
            else if ($('searchbrand').scrollTop + 8 * searchWidth < brandIndex * searchWidth)
                $('searchbrand').scrollTop = brandIndex * searchWidth - 7 * searchWidth;
        }

        window.getSelectedIndex = function(keycode) {
            var length = $$('#searchbrand li').length;
            if (keycode == 38 && brandIndex == 0)
                brandIndex = length - 1;
            else if (keycode == 40 && brandIndex == (length - 1))
                brandIndex = 0;
            else if (keycode == 38)
                brandIndex--;
            else if (keycode == 40)
                brandIndex++;
        }

        window.redirect = function(url_key, name) {
            $('brandsearch').value = name;
            window.location.href = '<?php echo $block->storeManager()->getStore()->getBaseUrl();?>' + url_key;
        }
    });
</script>


